package Modelo;
// Generated 18/03/2024 12:13:21 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.*;

/**
 * Alumnos generated by hbm2java
 */
public class Alumnos  implements java.io.Serializable {


     private int noCuentaAlumno;
     private Carreras carrerasByCarrera;
     private Carreras carrerasByGeneracion;
     private String nombre;
     private String paterno;
     private String materno;
     private String sexo;
     private Integer edad;
     private String direccion;
     private Long celular;
     private String correoElectronico;
     private Date fechaNacimiento;
     
    @ManyToOne
    @JoinColumn(name = "Carrera")
    private Carreras carrera;
    
    public Alumnos() {
    }

	
    public Alumnos(int noCuentaAlumno) {
        this.noCuentaAlumno = noCuentaAlumno;
    }
    public Alumnos(int noCuentaAlumno, Carreras carrerasByCarrera, Carreras carrerasByGeneracion, String nombre, String paterno, String materno, String sexo, Integer edad, String direccion, Long celular, String correoElectronico, Date fechaNacimiento) {
       this.noCuentaAlumno = noCuentaAlumno;
       this.carrerasByCarrera = carrerasByCarrera;
       this.carrerasByGeneracion = carrerasByGeneracion;
       this.nombre = nombre;
       this.paterno = paterno;
       this.materno = materno;
       this.sexo = sexo;
       this.edad = edad;
       this.direccion = direccion;
       this.celular = celular;
       this.correoElectronico = correoElectronico;
       this.fechaNacimiento = fechaNacimiento;
    }
   
    public int getNoCuentaAlumno() {
        return this.noCuentaAlumno;
    }
    
    public void setNoCuentaAlumno(int noCuentaAlumno) {
        this.noCuentaAlumno = noCuentaAlumno;
    }
    public Carreras getCarrerasByCarrera() {
        return this.carrerasByCarrera;
    }
    
    public void setCarrerasByCarrera(Carreras carrerasByCarrera) {
        this.carrerasByCarrera = carrerasByCarrera;
    }
    public Carreras getCarrerasByGeneracion() {
        return this.carrerasByGeneracion;
    }
    
    public void setCarrerasByGeneracion(Carreras carrerasByGeneracion) {
        this.carrerasByGeneracion = carrerasByGeneracion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPaterno() {
        return this.paterno;
    }
    
    public void setPaterno(String paterno) {
        this.paterno = paterno;
    }
    public String getMaterno() {
        return this.materno;
    }
    
    public void setMaterno(String materno) {
        this.materno = materno;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Long getCelular() {
        return this.celular;
    }
    
    public void setCelular(Long celular) {
        this.celular = celular;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

}
