package Modelo;
// Generated 18/03/2024 12:13:21 PM by Hibernate Tools 4.3.1



/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private int noCuentaProfesor;
     private Carreras carreras;
     private String nombre;
     private String paterno;
     private String materno;
     private String sexo;
     private Long celular;
     private String correoElectronico;
     private String cedulaProfesional;

    public Profesor() {
    }

	
    public Profesor(int noCuentaProfesor) {
        this.noCuentaProfesor = noCuentaProfesor;
    }
    public Profesor(int noCuentaProfesor, Carreras carreras, String nombre, String paterno, String materno, String sexo, Long celular, String correoElectronico, String cedulaProfesional) {
       this.noCuentaProfesor = noCuentaProfesor;
       this.carreras = carreras;
       this.nombre = nombre;
       this.paterno = paterno;
       this.materno = materno;
       this.sexo = sexo;
       this.celular = celular;
       this.correoElectronico = correoElectronico;
       this.cedulaProfesional = cedulaProfesional;
    }
   
    public int getNoCuentaProfesor() {
        return this.noCuentaProfesor;
    }
    
    public void setNoCuentaProfesor(int noCuentaProfesor) {
        this.noCuentaProfesor = noCuentaProfesor;
    }
    public Carreras getCarreras() {
        return this.carreras;
    }
    
    public void setCarreras(Carreras carreras) {
        this.carreras = carreras;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPaterno() {
        return this.paterno;
    }
    
    public void setPaterno(String paterno) {
        this.paterno = paterno;
    }
    public String getMaterno() {
        return this.materno;
    }
    
    public void setMaterno(String materno) {
        this.materno = materno;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Long getCelular() {
        return this.celular;
    }
    
    public void setCelular(Long celular) {
        this.celular = celular;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public String getCedulaProfesional() {
        return this.cedulaProfesional;
    }
    
    public void setCedulaProfesional(String cedulaProfesional) {
        this.cedulaProfesional = cedulaProfesional;
    }




}


