package Modelo;
// Generated 18/03/2024 12:13:21 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Trabajos generated by hbm2java
 */
public class Trabajos  implements java.io.Serializable {


     private int idTesis;
     private Carreras carrerasByGeneracion;
     private Carreras carrerasByCarrera;
     private Integer noCuentaAlumno;
     private Integer noCuentaProfesor;
     private String tema;
     private Date fechaPresentacion;
     private Date fechaEntrega;
     private Date fechaPublicacion;

    public Trabajos() {
    }

	
    public Trabajos(int idTesis) {
        this.idTesis = idTesis;
    }
    public Trabajos(int idTesis, Carreras carrerasByGeneracion, Carreras carrerasByCarrera, Integer noCuentaAlumno, Integer noCuentaProfesor, String tema, Date fechaPresentacion, Date fechaEntrega, Date fechaPublicacion) {
       this.idTesis = idTesis;
       this.carrerasByGeneracion = carrerasByGeneracion;
       this.carrerasByCarrera = carrerasByCarrera;
       this.noCuentaAlumno = noCuentaAlumno;
       this.noCuentaProfesor = noCuentaProfesor;
       this.tema = tema;
       this.fechaPresentacion = fechaPresentacion;
       this.fechaEntrega = fechaEntrega;
       this.fechaPublicacion = fechaPublicacion;
    }
   
    public int getIdTesis() {
        return this.idTesis;
    }
    
    public void setIdTesis(int idTesis) {
        this.idTesis = idTesis;
    }
    public Carreras getCarrerasByGeneracion() {
        return this.carrerasByGeneracion;
    }
    
    public void setCarrerasByGeneracion(Carreras carrerasByGeneracion) {
        this.carrerasByGeneracion = carrerasByGeneracion;
    }
    public Carreras getCarrerasByCarrera() {
        return this.carrerasByCarrera;
    }
    
    public void setCarrerasByCarrera(Carreras carrerasByCarrera) {
        this.carrerasByCarrera = carrerasByCarrera;
    }
    public Integer getNoCuentaAlumno() {
        return this.noCuentaAlumno;
    }
    
    public void setNoCuentaAlumno(Integer noCuentaAlumno) {
        this.noCuentaAlumno = noCuentaAlumno;
    }
    public Integer getNoCuentaProfesor() {
        return this.noCuentaProfesor;
    }
    
    public void setNoCuentaProfesor(Integer noCuentaProfesor) {
        this.noCuentaProfesor = noCuentaProfesor;
    }
    public String getTema() {
        return this.tema;
    }
    
    public void setTema(String tema) {
        this.tema = tema;
    }
    public Date getFechaPresentacion() {
        return this.fechaPresentacion;
    }
    
    public void setFechaPresentacion(Date fechaPresentacion) {
        this.fechaPresentacion = fechaPresentacion;
    }
    public Date getFechaEntrega() {
        return this.fechaEntrega;
    }
    
    public void setFechaEntrega(Date fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }
    public Date getFechaPublicacion() {
        return this.fechaPublicacion;
    }
    
    public void setFechaPublicacion(Date fechaPublicacion) {
        this.fechaPublicacion = fechaPublicacion;
    }




}


