package Modelo;
// Generated 28/03/2024 09:57:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Alumnos generated by hbm2java
 */
public class Alumnos  implements java.io.Serializable {


     private Integer noCuentaAlumno;
     private Carreras carreras;
     private String nombre;
     private String paterno;
     private String materno;
     private String sexo;
     private Integer edad;
     private String direccion;
     private Long celular;
     private String correoElectronico;
     private Date fechaNacimiento;
     private String generacion;
     private Set<Trabajos> trabajoses = new HashSet<Trabajos>(0);

    public Alumnos() {
    }

	
    public Alumnos(String nombre, String paterno, String materno) {
        this.nombre = nombre;
        this.paterno = paterno;
        this.materno = materno;
    }
    public Alumnos(Carreras carreras, String nombre, String paterno, String materno, String sexo, Integer edad, String direccion, Long celular, String correoElectronico, Date fechaNacimiento, String generacion, Set<Trabajos> trabajoses) {
       this.carreras = carreras;
       this.nombre = nombre;
       this.paterno = paterno;
       this.materno = materno;
       this.sexo = sexo;
       this.edad = edad;
       this.direccion = direccion;
       this.celular = celular;
       this.correoElectronico = correoElectronico;
       this.fechaNacimiento = fechaNacimiento;
       this.generacion = generacion;
       this.trabajoses = trabajoses;
    }
   
    public Integer getNoCuentaAlumno() {
        return this.noCuentaAlumno;
    }
    
    public void setNoCuentaAlumno(Integer noCuentaAlumno) {
        this.noCuentaAlumno = noCuentaAlumno;
    }
    public Carreras getCarreras() {
        return this.carreras;
    }
    
    public void setCarreras(Carreras carreras) {
        this.carreras = carreras;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPaterno() {
        return this.paterno;
    }
    
    public void setPaterno(String paterno) {
        this.paterno = paterno;
    }
    public String getMaterno() {
        return this.materno;
    }
    
    public void setMaterno(String materno) {
        this.materno = materno;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Long getCelular() {
        return this.celular;
    }
    
    public void setCelular(Long celular) {
        this.celular = celular;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getGeneracion() {
        return this.generacion;
    }
    
    public void setGeneracion(String generacion) {
        this.generacion = generacion;
    }
    public Set<Trabajos> getTrabajoses() {
        return this.trabajoses;
    }
    
    public void setTrabajoses(Set<Trabajos> trabajoses) {
        this.trabajoses = trabajoses;
    }




}


