package Modelo;
// Generated 28/03/2024 09:57:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Carreras generated by hbm2java
 */
public class Carreras  implements java.io.Serializable {


     private Integer carreraId;
     private String nombre;
     private String generacion;
     private Set<Alumnos> alumnoses = new HashSet<Alumnos>(0);
     private Set<Profesores> profesoreses = new HashSet<Profesores>(0);

    public Carreras() {
    }

	
    public Carreras(String nombre) {
        this.nombre = nombre;
    }
    public Carreras(String nombre, String generacion, Set<Alumnos> alumnoses, Set<Profesores> profesoreses) {
       this.nombre = nombre;
       this.generacion = generacion;
       this.alumnoses = alumnoses;
       this.profesoreses = profesoreses;
    }
   
    public Integer getCarreraId() {
        return this.carreraId;
    }
    
    public void setCarreraId(Integer carreraId) {
        this.carreraId = carreraId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getGeneracion() {
        return this.generacion;
    }
    
    public void setGeneracion(String generacion) {
        this.generacion = generacion;
    }
    public Set<Alumnos> getAlumnoses() {
        return this.alumnoses;
    }
    
    public void setAlumnoses(Set<Alumnos> alumnoses) {
        this.alumnoses = alumnoses;
    }
    public Set<Profesores> getProfesoreses() {
        return this.profesoreses;
    }
    
    public void setProfesoreses(Set<Profesores> profesoreses) {
        this.profesoreses = profesoreses;
    }




}


