package Modelo;
// Generated 28/03/2024 09:57:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profesores generated by hbm2java
 */
public class Profesores  implements java.io.Serializable {


     private Integer noCuentaProfesor;
     private Carreras carreras;
     private String nombre;
     private String paterno;
     private String materno;
     private String sexo;
     private Long celular;
     private String correoElectronico;
     private String cedulaProfesional;
     private Set<Trabajos> trabajoses = new HashSet<Trabajos>(0);

    public Profesores() {
        carreras = new Carreras();
    }

	
    public Profesores(String nombre, String paterno, String materno) {
        this.nombre = nombre;
        this.paterno = paterno;
        this.materno = materno;
    }
    public Profesores(Carreras carreras, String nombre, String paterno, String materno, String sexo, Long celular, String correoElectronico, String cedulaProfesional, Set<Trabajos> trabajoses) {
       this.carreras = carreras;
       this.nombre = nombre;
       this.paterno = paterno;
       this.materno = materno;
       this.sexo = sexo;
       this.celular = celular;
       this.correoElectronico = correoElectronico;
       this.cedulaProfesional = cedulaProfesional;
       this.trabajoses = trabajoses;
    }
   
    public Integer getNoCuentaProfesor() {
        return this.noCuentaProfesor;
    }
    
    public void setNoCuentaProfesor(Integer noCuentaProfesor) {
        this.noCuentaProfesor = noCuentaProfesor;
    }
    public Carreras getCarreras() {
        return this.carreras;
    }
    
    public void setCarreras(Carreras carreras) {
        this.carreras = carreras;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPaterno() {
        return this.paterno;
    }
    
    public void setPaterno(String paterno) {
        this.paterno = paterno;
    }
    public String getMaterno() {
        return this.materno;
    }
    
    public void setMaterno(String materno) {
        this.materno = materno;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Long getCelular() {
        return this.celular;
    }
    
    public void setCelular(Long celular) {
        this.celular = celular;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public String getCedulaProfesional() {
        return this.cedulaProfesional;
    }
    
    public void setCedulaProfesional(String cedulaProfesional) {
        this.cedulaProfesional = cedulaProfesional;
    }
    public Set<Trabajos> getTrabajoses() {
        return this.trabajoses;
    }
    
    public void setTrabajoses(Set<Trabajos> trabajoses) {
        this.trabajoses = trabajoses;
    }




}


